site_name: Rocket Validator Documentation
site_url: https://docs.rocketvalidator.com/
site_description: Documentation site for Rocket Validator - automated accessibility scanner for large sites
nav:
  - Welcome: index.md
  - Quick Start: quick-start.md
  - Summary Reports: summary-reports.md
  - Broken Links Checker: broken-links-checker.md
  - Rate Limiting: rate-limits.md
  - Scheduling Reports: scheduling.md
  - Deploy Hooks: deploy-hooks.md
  - Domain Stats: domain-stats.md
  - Muting Issues: muting.md
  - Performance Tips: performance-tips.md
  - User Agents: user-agents.md
  - Google Analytics: google-analytics.md
  - Validating your local server: how-to-validate-your-local-server.md
  - Changelog: changelog.md
  - FAQs: faqs.md
  - API:
    - Introduction: api/index.md
    - Authorization: api/authorization.md
    - Pagination: api/pagination.md
    - Resources: api/resources.md
    - Reports: api/reports.md
    - Web Pages: api/web_pages.md
    - Accessibility Issues: api/a11y_issues.md
    - HTML Issues: api/html_issues.md
    - Common Accessibility Issues: api/common_a11y_issues.md
    - Common HTML Issues: api/common_html_issues.md
    - Schedules: api/schedules.md
    - Mutings: api/mutings.md
    - Client Libraries: api/client-libraries.md
    - Changelog: api/changelog.md
theme:
  name: material
  features:
    - navigation.instant
  custom_dir: overrides
  language: en
  logo: img/rocket-icon-300x300.png
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rocketvalidator
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rocketvalidator
    - icon: fontawesome/brands/linkedin
      link: https://pr.linkedin.com/company/rocket-validator
markdown_extensions:
- admonition
- pymdownx.superfences
- pymdownx.tabbed
- codehilite:
    guess_lang: false
    css_class: "codehilite"
extra_css:
    - css/codehilite/borland.css
    - css/extra.css
extra_javascript:
    - js/extra.js