site_name: Rocket Validator Documentation
site_url: https://docs.rocketvalidator.com/
nav:
    - Quick Start: index.md
    - Summary Reports: summary-reports.md
    - Broken Links Checker: broken-links-checker.md
    - Rate Limiting: rate-limits.md
    - Scheduling Reports: scheduling.md
    - Deploy Hooks: deploy-hooks.md
    - Validation Charts: validation-charts.md
    - Muting Issues: muting.md
    - Performance Tips: performance-tips.md
    - User Agents: user-agents.md
    - Validating your local server: how-to-validate-your-local-server.md
    - FAQs: faqs.md
theme:
  name: material
  language: en
  logo: img/rocket-icon-300x300.png
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rocketvalidator
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rocketvalidator
    - icon: fontawesome/brands/linkedin
      link: https://pr.linkedin.com/company/rocket-validator
google_analytics:
  - UA-81204018-1
  - auto
markdown_extensions:
- admonition
- pymdownx.superfences
- codehilite:
    guess_lang: false
    css_class: "codehilite"
extra_css:
    - css/codehilite/borland.css
    - css/extra.css
extra_javascript:
    - js/extra.js
